languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false

exclude_paths:
- ".db/*"
- "docs/**/*"

# -------------------------------------------------------------------- #
# Disabled, because the version of eslint used in Code Climate is old. #
# babel-eslint parser does not work, and cannot use new rules.         #
# see https://github.com/codeclimate/codeclimate-eslint/issues/10      #
# -------------------------------------------------------------------- #
# engines:
#   eslint:
#     enabled: true
#
# ratings:
#   paths:
#   - "src/**"
#   - "tasks/**"
#   - "**.js"
#   - "**.jsx"
