languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false

exclude_paths:
- ".db/*"
- "docs/**/*"

# --------------------------------------------------------------- #
# Disabled, because babel-eslint parser does not work atm.        #
# see https://github.com/codeclimate/codeclimate-eslint/issues/10 #
# --------------------------------------------------------------- #
# engines:
#   eslint:
#     enabled: true
# ratings:
#   paths:
#   - "src/**"
#   - "tasks/**"
#   - "**.js"
#   - "**.jsx"
